### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by aohorodnyk** [dima117/thinking-home#3]
Hello,

Could you add README.md (move and format description from readme.txt to readme.md)?

Thanks

**Comment by dima117** [comment]
Hello,

I will add readme soon. Please write me what information would you like to see in readme.

**Comment by dima117** [comment]
You can find detailed information about the project at http://thinking-home.ru/system

**Comment by DropSQL** [comment]
I like see those information:
 1) Can I use mono and linux for your application?
 2) Short description about thinking-home about features which you use and technologies
 3) Links to http://thinking-home.ru/, tutorial(s) and other helpful information

P.S. I know Russian language

**Comment by dima117** [comment]
Readme & docs were added.
